import Head from 'next/head'
import {
  Layout, 
  Header, 
  MissionVision, 
  Services, 
  AboutSnippet, 
  RecentBlogPosts,
  Gallery} from "../components/Layout";
const Home = () =>{
  return (
    <div>
      <Head>
        <title>WOM</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" />
      </Head>
      <main>
        <Layout>
          <Header />
          <AboutSnippet />
          <MissionVision />
          <Services />
          <RecentBlogPosts />
          {/* <Gallery /> */}
        </Layout>
      </main>
    </div>
  )
}
export default Home;
